MedixCollege/Controllers/CampusesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MedixCollege.Controllers
{
    public class CampusesController : Controller
    {
        // GET: All Campuses
        public ActionResult Index()
        {
            ViewBag.HeroText = "";
            ViewBag.BodyHeaderText = "";

            ViewBag.SideHeader = "Test";
            ViewBag.SideSubHeader1 = "Test1";
            ViewBag.SideSubText1 = "Test2";
            ViewBag.SideSubHeader2 = "Test3";
            ViewBag.SideSubText2 = "Test4";
            ViewBag.SideSubHeader3 = "Test5";
            ViewBag.SideSubText3 = "Test6";

            return View();
        }

        // GET: Brampton
        public ActionResult Brampton()
        {
            return View();
        }

        // GET: Brantford
        public ActionResult Brantford()
        {
            return View();
        }

        // GET: Kitchener
        public ActionResult Kitchener()
        {
            return View();
        }

        // GET: London
        public ActionResult London()
        {
            return View();
        }

        // GET: Scarborough
        public ActionResult Scarborough()
        {
            return View();
        }

        // GET: Toronto
        public ActionResult Toronto()
        {
            return View();
        }
    }
}

MedixCollege/Controllers/CareerServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MedixCollege.Controllers
{
    public class CareerServicesController : Controller
    {
        // GET: CareerServices
        public ActionResult Index()
        {
            ViewBag.HeroText = "";
            ViewBag.BodyHeaderText = "";

            ViewBag.SideHeader = "Test";
            ViewBag.SideSubHeader1 = "Test1";
            ViewBag.SideSubText1 = "Test2";
            ViewBag.SideSubHeader2 = "Test3";
            ViewBag.SideSubText2 = "Test4";
            ViewBag.SideSubHeader3 = "Test5";
            ViewBag.SideSubText3 = "Test6";

            return View();
        }

        // GET: MedixAdvantage
        public ActionResult NATSAdvantage()
        {
            return View();
        }

        public ActionResult JobSearchTips()
        {
            return View();
        }

        public ActionResult ResumeTips()
        {
            return View();
        }

        public ActionResult InterviewTips()
        {
            return View();
        }

        public ActionResult ProfessionalTips()
        {
            return View();
        }

        public ActionResult HireAGrad()
        {
            return View();
        }

        public ActionResult KPIandDefault()
        {
            return View();
        }

        public ActionResult CanadaJobGrant()
        {
            return View();
        } 
    }
}

MedixCollege/Controllers/ProgramsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MedixCollege.Controllers
{
    public class ProgramsController : Controller
    {
        // GET: Programs
        public ActionResult Index()
        {
            ViewBag.HeroText = "";
            ViewBag.BodyHeaderText = "";

            ViewBag.SideHeader = "Test";
            ViewBag.SideSubHeader1 = "Test1";
            ViewBag.SideSubText1 = "Test2";
            ViewBag.SideSubHeader2 = "Test3";
            ViewBag.SideSubText2 = "Test4";
            ViewBag.SideSubHeader3 = "Test5";
            ViewBag.SideSubText3 = "Test6";

            return View();
        }

        // GET: HVACTechnician
        public ActionResult HVACTechnician()
        {
            return View();
        }

        // GET: Welding
        public ActionResult Welding()
        {
            return View();
        }

        // GET: SolarEnergyTechnician
        public ActionResult SolarEnergyTechnician()
        {
            return View();
        }

        // GET: Cabinetmaking
        public ActionResult Cabinetmaking()
        {
            return View();
        }

        // GET: HomeRenovationTechnician
        public ActionResult HomeRenovationTechnician()
        {
            return View();
        }

        // GET: IndustrialAndCommericalMaintenance
        public ActionResult IndustrialAndCommericalMaintenance()
        {
            return View();
        }

        // GET: MotorcycleAndSmallEngineRepair
        public ActionResult MotorcycleAndSmallEngineRepair()
        {
            return View();
        }

        // GET: ConstructionAndMaintenanceElectrician
        public ActionResult ConstructionAndMaintenanceElectrician()
        {
            return View();
        }

        // GET: ElectricalTechnology
        public ActionResult ElectricalTechnology()
        {
            return View();
        }

        // GET: All Programs
        public ActionResult AllPrograms()
        {
            ViewBag.SideHeader = "Test";
            ViewBag.SideSubHeader1 = "Test1";
            ViewBag.SideSubText1 = "Test2";
            ViewBag.SideSubHeader2 = "Test3";
            ViewBag.SideSubText2 = "Test4";
            ViewBag.SideSubHeader3 = "Test5";
            ViewBag.SideSubText3 = "Test6";

            return View();
        }
    }
}

MedixCollege/Views/CareerServices/CanadaJobGrant.cshtml
@{
    Layout = "~/Views/CareerServices/_CareerServicesLayout.cshtml";
}

@{
    ViewBag.Title = "NATS Advantage";
    ViewBag.PageDescription = "Medix Advantage";
    ViewBag.HeaderTitle = "NATS Advantage";
}


<div class="col-sm-12 no-padding botMARG">
    <h1 class="contentPageH1">CANADA JOB GRANT</h1>
    <ol class="breadcrumb">
        <li class="contentp">@Html.ActionLink("Home", "Index", "Home")</li>
        <li class="active contentp">Canada Job Grant </li>
    </ol>


</div>

<div class="col-sm-8 mid-padding">




    <h1 class="contentH1">Key details for Employers and Employees:</h1><hr class="hrp" />
    <p class="contentp">
        The Canada Job Grant covers two-thirds of the cost of training up to a maximum of $10,000 that is contributed by the government.
        <br /><br />
        The training is intended for employed individuals acquiring new skills for their current job, or to prepare for another job with the same employer, and for unemployed individuals seeking a new job.
        <br /><br />
        The employer must have a job available at the end of the training for the individual being trained.!
        <br /><br />
        Training must not exceed one year in duration and must be provided by one of the following:
        <ul>

            <li>Colleges of applied arts and technology</li>
            <li>Publicly-assisted universities</li>
            <li>School boards</li>
            <li>Private trainers operating in compliance with the Private Career Colleges Act, 2005</li>
            <li>Union-based training centres</li>
            <li>Product vendors</li>
        </ul>
    </p><br />
    <h1 class="contentH1">Confirm Your Eligibility & Streamline the Application Process </h1><hr class="hrp" />
    <p class="contentp">
        The Canada Job Grant is issued through a wide variety of service providers across Canada (excl. Quebec), each with their own pool of funds. It’s critical that your business profile, timelines, budget, and project impacts are all aligned with your local service provider’s priorities for funding. For comprehensive funding application support services, please reach out to our trusted partner, Mentor Works Ltd. by calling 1-888-599-3111 ext.115 or emailing jeffd@mentorworks.ca to speak to Jeff Dumart, Business Development Analyst at Mentor Works.
        <br /><br />
        Click below to go to<br /><br />
        <a href="http://www.esdc.gc.ca/en/job_grant/index.page " target="_blank"><img src="~/Content/images/canadajobgrant.jpg" class="img-responsive" /></a>
    </p>



    <br />
    <button type="button" class="btn btn-default btn-lg btn-block contentH2"><span class="glyphicon glyphicon-send"></span>&nbsp;&nbsp;@Html.ActionLink("GO TO PROGRAM DIRECTORY", "AllPrograms", "Programs")</button>
    <br />
    <button type="button" class="btn btn-default btn-lg btn-block contentH2"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;&nbsp;@Html.ActionLink("GO TO CAMPUS DIRECTORY", "Index", "Campuses")</button>
    <br />
</div>




<div class="col-sm-4 pull-right no-padding">
    <div class="panel panel-default bluePANEL2">

        <div class="panel-body">
            <h1 class="contentH1whitemain text-center">
                <span class="glyphicon glyphicon-comment 1blueGoldBorder"></span>&nbsp; Ask a Question
            </h1><hr class="hrpw3" />
            <div class="row formWrapper overquestionsForm2">
                <form id="discoverMedixQuestionsForm" name="discoverMedixQuestionsForm" data-parsley-validate="" class="questionsForm" method="post" action="/home/askquestion">
                    <input type="hidden" name="ORGID" value="240" />
                    <input type="hidden" name="MailListID" value="240001" />
                    <div class="input-group spacer-top">
                        <label class="pull-left contentpw">First Name: <span class="text-danger">*</span></label>
                        <input type="text" class="form-control pull-right" name="FirstName" required="">
                    </div>
                    <div class="input-group spacer-top">
                        <label class="pull-left contentpw">Email: <span class="text-danger">*</span></label>
                        <input type="email" class="form-control pull-right" name="Email" required="">
                    </div>
                    <div class="input-group spacer-top">
                        <label class="pull-left contentpw">Telephone: <span class="text-danger">*</span></label>
                        <input type="text" class="form-control pull-right" name="Telephone" required="">
                    </div>
                    <div class="input-group spacer-top">
                        <label class="pull-left contentpw">Location: <span class="text-danger" required="">*</span></label>
                        <select class="form-control pull-right" name="CampusID">
                            <option value="0">Select</option>
                            <option value="24004">Brampton-NATS</option>
                            <option value="24001">London-NATS</option>
                            <option value="240">Toronto</option>
                        </select>
                    </div>
                    <div class="input-group spacer-top">
                        <label class="pull-left contentpw">Program: <span class="text-danger">*</span></label>
                        <select class="form-control pull-right" name="ProgramID">
                            <option class="0 24004 24001 240" value="0">Select</option>
                            <option class="0 24004 24001" value="39064">Cabinetmaking</option>
                            <option class="0 24004" value="40332">Construction Maintenance Electrician Pre-Apprenticeship</option>
                            <option class="0 24004 24001" value="39061">Electrical Technology</option>
                            <option class="0 24004 24001" value="39060">Home Renovation Technician</option>
                            <option class="0 24004 24001" value="39062">HVAC Technician</option>
                            <option class="0 24001" value="40294">Motorcycle & Small Engine Repair</option>
                            <option class="0 24004 24001 240" value="39737">Solar Energy Technician</option>
                            <option class="0 24004 24001" value="39063">Welding Technology</option>
                        </select>
                    </div>
                    <div class="input-group spacer-top">
                        <label class="pull-left contentpw">Comments: </label>
                        <textarea class="form-control pull-right" name="Comment2"></textarea>
                    </div>
                    <div class="small-text spacer-top text-center contentpw">
                        Please contact me with more information relating to the school and program(s). I understand I may cancel my consent at anytime.
                    </div>
                    <div class="text-center">
                        <input id="applyNowSubmit" type="submit" value="Submit" class="btn popup-form-button spacer-top btn-block" />
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

MedixCollege/Views/CareerServices/Index.cshtml
@{
    Layout = "~/Views/CareerServices/_CareerServicesLayout.cshtml";
}

@{
    ViewBag.Title = "Career Services";
    ViewBag.PageDescription = "Employment counselling and job search training is provided for all students during their program by scheduled classroom lectures and ongoing individualized counselling";
    ViewBag.HeaderTitle = "Career Services";
}

<div class="col-sm-12 no-padding botMARG">
    <h1 class="contentPageH1">CAREER SERVICES</h1>
    <ol class="breadcrumb">
        <li class="contentp">@Html.ActionLink("Home", "Index", "Home")</li>
        <li class="active contentp">Career Services</li>
    </ol><img class="img-responsive" width="100%" src="~/Content/images/career-services-mainpage.jpg" alt="job seeker in an interview with an employer" />

</div>

<div class="col-sm-8 mid-padding">

    <div class="panel panel-default">
        <div class="panel-body">
            <h1 class="contentH1">Career Services at North American Trade Schools</h1>
<hr class="hrp" /><p class="contentp">
    Employment counselling and job search training is provided for all students during their program by

    scheduled classroom lectures and ongoing individualized counselling. The School remains a permanent

    source of employment search assistance for all graduates. The placement department prepares each

    student to:
</p>
<ul class="contentp">
    <li>Create cover letter, resume and other effective portfolio material.</li>

    <li>Conduct an employment interview including proper follow-up activities.</li>

    <li>Analyze employment opportunities and market trends.</li>

    <li>Utilize resources for locating prospective employers.</li>

    <li>Analyze employment benefits and career advancement opportunities.</li>
</ul>
<br />

<p class="contentp">
    North American Trade Schools Graduates have been hired in all industries of the residential, commercial and industrial sectors in all of our offered programs. Our graduates have been hired in companies all across Canada. Some of the employers of North American Trade Schools graduates include:
</p>
        </div>
    </div>

    
    <div class="panel panel-default">
        <div class="panel-body">
            <h1 class="contentH1">Calling all Employers!</h1>
<hr class="hrp" /><p class="contentp">
    Are you are looking for a solution to help you meet the demands of your organization? Why not hire a North American Trade Schools graduate. To find out more about what openings our students are a great fit for contact the Employment Relations consultant at the School.
</p>
        </div>
    </div>




    

    <button type="button" class="btn btn-default btn-lg btn-block contentH2"><span class="glyphicon glyphicon-send"></span>&nbsp;&nbsp;@Html.ActionLink("GO TO PROGRAM DIRECTORY", "AllPrograms", "Programs")</button>
    <br />
    <button type="button" class="btn btn-default btn-lg btn-block contentH2"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;&nbsp;@Html.ActionLink("GO TO CAMPUS DIRECTORY", "Index", "Campuses")</button>
    <br />
</div>

<div class="col-sm-4 pull-right no-padding">
    <div class="panel panel-default bluePANEL2">

        <div class="panel-body">
            <h1 class="contentH1whitemain text-center">
                <span class="glyphicon glyphicon-comment 1blueGoldBorder"></span>&nbsp; Ask a Question
            </h1><hr class="hrpw3" />
            <div class="row formWrapper overquestionsForm2">
                <form id="discoverMedixQuestionsForm" name="discoverMedixQuestionsForm" data-parsley-validate="" class="questionsForm" method="post" action="/home/askquestion">
                    <input type="hidden" name="ORGID" value="240" />
                    <input type="hidden" name="MailListID" value="240001" />
                    <div class="input-group spacer-top">
                        <label class="pull-left contentpw">First Name: <span class="text-danger">*</span></label>
                        <input type="text" class="form-control pull-right" name="FirstName" required="">
                    </div>
                    <div class="input-group spacer-top">
                        <label class="pull-left contentpw">Email: <span class="text-danger">*</span></label>
                        <input type="email" class="form-control pull-right" name="Email" required="">
                    </div>
                    <div class="input-group spacer-top">
                        <label class="pull-left contentpw">Telephone: <span class="text-danger">*</span></label>
                        <input type="text" class="form-control pull-right" name="Telephone" required="">
                    </div>
                    <div class="input-group spacer-top">
                        <label class="pull-left contentpw">Location: <span class="text-danger" required="">*</span></label>
                        <select class="form-control pull-right" name="CampusID">
                            <option value="0">Select</option>
                            <option value="24004">Brampton-NATS</option>
                            <option value="24001">London-NATS</option>
                            <option value="240">Toronto</option>
                        </select>
                    </div>
                    <div class="input-group spacer-top">
                        <label class="pull-left contentpw">Program: <span class="text-danger">*</span></label>
                        <select class="form-control pull-right" name="ProgramID">
                            <option class="0 24004 24001 240" value="0">Select</option>
                            <option class="0 24004 24001" value="39064">Cabinetmaking</option>
                            <option class="0 24004" value="40332">Construction Maintenance Electrician Pre-Apprenticeship</option>
                            <option class="0 24004 24001" value="39061">Electrical Technology</option>
                            <option class="0 24004 24001" value="39060">Home Renovation Technician</option>
                            <option class="0 24004 24001" value="39062">HVAC Technician</option>
                            <option class="0 24001" value="40294">Motorcycle & Small Engine Repair</option>
                            <option class="0 24004 24001 240" value="39737">Solar Energy Technician</option>
                            <option class="0 24004 24001" value="39063">Welding Technology</option>
                        </select>
                    </div>
                    <div class="input-group spacer-top">
                        <label class="pull-left contentpw">Comments: </label>
                        <textarea class="form-control pull-right" name="Comment2"></textarea>
                    </div>
                    <div class="small-text spacer-top text-center contentpw">
                        Please contact me with more information relating to the school and program(s). I understand I may cancel my consent at anytime.
                    </div>
                    <div class="text-center">
                        <input id="applyNowSubmit" type="submit" value="Submit" class="btn popup-form-button spacer-top btn-block" />
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

MedixCollege/Views/CareerServices/MedixAdvantage.cshtml
@{
    Layout = "~/Views/CareerServices/_CareerServicesLayout.cshtml";
}

@{
    ViewBag.Title = "NATS Advantage";
    ViewBag.PageDescription = "Medix Advantage";
    ViewBag.HeaderTitle = "NATS Advantage";
}
<div class="col-sm-12">
    <h1 class="contentPageH1">NATS ADVANTAGE</h1>
    <ol class="breadcrumb">
        <li class="contentp">@Html.ActionLink("Home", "Index", "Home")</li>
        <li class="contentp">@Html.ActionLink("Career Services Home", "Index", "CareerServices")</li>
        <li class="active contentp">NATS Advantage</li>
    </ol>

</div>

<div class="col-sm-8 mid-padding">

    <div class="panel panel-default">
        <div class="panel-body">
            <h1 class="contentH1">What is the NATS Advantage?</h1>

            <hr class="hrp" />
            <ol class="contentp">
                <li>Powerful tools for identifying career opportunities</li>

                <li>
                    Significant Advantage - NATS Advantage gives our students a significant advantage over

                    individuals who do not have access to this technology
                </li>

                <li>Web-based solution is integrated into the NATS web site</li>
            </ol>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-body">

            <h1 class="contentH1">What are the benefits to the NATS Advantage?</h1><hr class="hrp" />

            <ol class="contentp">
                <li>Provides powerful tools for a targeted job search campaign</li>

                <li>NATS Advantage is designed for the job seeker—it is unlike employer-funded job sites</li>

                <li>Consolidates new job postings from thousands of independent local sources</li>

                <li>Delivers access to a much larger number of local job opportunities than any other source</li>

                <li>
                    Reduces the number of missed job opportunities—simply impossible for an individual to

                    identify and then keep an eye on all the sources monitored by MEDIX Advantage
                </li>

                <li>
                    Most job opportunities captured by MEDIX Advantage are not available on any employer-

                    sponsored sites
                </li>
            </ol>
        </div>
    </div>

    <br />
    <p>

        <iframe src="http://www.careeraim.com/CareerSite1/login.aspx" width="100%" height="600"
                border="0"></iframe>
    </p>
</div>

<div class="col-sm-4 pull-right no-padding">
    <div class="panel panel-default">

        <div class="panel-body">
            <h1 class="contentH1 text-center">
                <span class="glyphicon glyphicon-comment 1blueGoldBorder"></span>&nbsp; Ask a Question
            </h1><hr class="hrpblue" />
            <div class="row formWrapper overquestionsForm">


                <form id="discoverMedixQuestionsForm" name="discoverMedixQuestionsForm" class="questionsForm" method="post" action="/home/askquestion">
                    <input type="hidden" name="ORGID" value="240" />
                    <input type="hidden" name="MailListID" value="240001" />
                    <div class="input-group spacer-top">
                        <label class="pull-left contentp">First Name: <span class="text-danger">*</span></label>
                        <input type="text" class="form-control pull-right" name="FirstName">
                    </div>
                    <div class="input-group spacer-top">
                        <label class="pull-left contentp">Email: <span class="text-danger">*</span></label>
                        <input type="email" class="form-control pull-right" name="Email">
                    </div>
                    <div class="input-group spacer-top">
                        <label class="pull-left contentp">Location: <span class="text-danger">*</span></label>
                        <select class="form-control pull-right" name="CampusID">
                            <option value="0">Select</option>
                            <option value="24004">Brampton-NATS</option>
                            <option value="24001">London-NATS</option>
                            <option value="240">Toronto</option>
                        </select>
                    </div>
                    <div class="input-group spacer-top">
                        <label class="pull-left contentp">Program: <span class="text-danger">*</span></label>
                        <select class="form-control pull-right" name="ProgramID">
                            <option class="0 24004 24001 240" value="0">Select</option>
                            <option class="0 24004 24001" value="39064">Cabinetmaking</option>
                            <option class="0 24004" value="40332">Construction Maintenance Electrician Pre-Apprenticeship</option>
                            <option class="0 24004 24001" value="39061">Electrical Technology</option>
                            <option class="0 24004 24001" value="39060">Home Renovation Technician</option>
                            <option class="0 24004 24001" value="39062">HVAC Technician</option>
                            <option class="0 24001" value="40294">Motorcycle & Small Engine Repair</option>
                            <option class="0 24004 24001 240" value="39737">Solar Energy Technician</option>
                            <option class="0 24004 24001" value="39063">Welding Technology</option>
                        </select>
                    </div>
                    <div class="input-group spacer-top">
                        <label class="pull-left contentp">Comments: </label>
                        <textarea class="form-control pull-right" name="Comment2"></textarea>
                    </div>
                    <div class="small-text spacer-top text-center grayColor contentp">
                        Please contact me with more information relating to the school and program(s). I understand I may cancel my consent at anytime.
                    </div>
                    <div class="text-center">
                        <input id="applyNowSubmit" type="submit" value="Submit" class="btn popup-form-button spacer-top btn-block" />
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

MedixCollege/Views/CareerServices/_CareerServicesLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<br />
<div class="container">
    <div class="heroWrapper">
        @ViewBag.HeroText
    </div>
    <div class="leftMenuWrapper col-md-3 custom-collapse">
        <button class="btn-brand-white collapse-toggle visible-xs" type="button" data-toggle="collapse" data-parent="custom-collapse" data-target="#side-menu-career">
            <span class=""><span class="glyphicon glyphicon-align-justify"></span></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <ul class="leftMenu list-unstyled collapse" id="side-menu-career">
            <li class="item header">@Html.ActionLink("CAREER SERVICES", "Index", "CareerServices")</li>
            <li class="item side-menu-h2">@Html.ActionLink("Careers Services Home", "Index", "CareerServices")</li>
            <li class="item side-menu-h2">@Html.ActionLink("Hire a Grad", "HireAGrad", "Home")</li>
            <li class="item side-menu-h2">@Html.ActionLink("NATS Advantage", "NATSAdvantage", "CareerServices")</li>
            <li class="item side-menu-h2">@Html.ActionLink("KPI and Default Rates", "KPIandDefault", "CareerServices")</li>
            <br />
            <li class="item btn btn-brand btn-block spacer-top" id="askQuestion">Ask a Question</li>
            <li class="item btn btn-brand btn-block" id="requestCatalogue">Request Catalogue</li>
        </ul>
        <br />
        <a href="https://natradeschools.virtualadmissions.com/?lead_src=w-sidebar" target="_blank">
            <img class="img-responsive" width="100%" src="~/Content/images/nats-vaa.jpg" alt="virtual admissions questionnaire for NATS" />
        </a>
    </div>

    <div class="col-sm-9 pull-right">
        <div class="contentBody">
            <div class="row bodyHeaderWrapper">
                @ViewBag.BodyHeaderText
            </div>
            <div class="row">
                @RenderBody()
            </div>
        </div>
    </div>

    <div class="clearfix"></div>
    <br />
</div>


<script>
    $(document).ready(function () {
        $('#applyOnline').click(function () {
            $('.popup-form-wrapper').hide();
            $('#applyNowWrapper').show();
            $('.form-overlay').slideDown()
        });

        $('#requestCatalogue').click(function () {
            $('.popup-form-wrapper').hide();
            $('#requestCatalogueWrapper').show();
            $('.form-overlay').slideDown()
        });

        $('#askQuestion').click(function () {
            $('.popup-form-wrapper').hide();
            $('#askQuestionWrapper').show();
            $('.form-overlay').slideDown()
        });
    });

    $(window).bind("pageshow", function () {
        var forms = $("form");
        forms.each(function (i) {
            forms[i].reset();
        });
    });
</script>