MedixCollege/Controllers/DiscoverMedixController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MedixCollege.Controllers
{
    public class DiscoverMedixController : Controller
    {
        // GET: DiscoverMedix
        public ActionResult Index()
        {
            ViewBag.HeroText = "";
            ViewBag.BodyHeaderText = "";

            ViewBag.SideHeader = "Test";
            ViewBag.SideSubHeader1 = "Test1";
            ViewBag.SideSubText1 = "Test2";
            ViewBag.SideSubHeader2 = "Test3";
            ViewBag.SideSubText2 = "Test4";
            ViewBag.SideSubHeader3 = "Test5";
            ViewBag.SideSubText3 = "Test6";

            return View();
        }

        // GET: History
        public ActionResult History()
        {
            return View();
        }

        // GET: Laptop Initiative
        public ActionResult LaptopInitiative()
        {
            return View();
        }

        // GET: Transcript Request
        public ActionResult TranscriptRequest()
        {
            return View();
        }

        public ActionResult VirtualTour()
        {
            return View();
        }

        public ActionResult CareersAtMedix()
        {
            return View();
        }
    }
}

MedixCollege/Views/DiscoverMedix/History.cshtml
@{
    Layout = "~/Views/DiscoverMedix/_DiscoverMedixLayout.cshtml";
}

@{
    ViewBag.Title = "History";
    ViewBag.PageDescription = "Medix College has experience exciting growth across southern Ontario. Find out how it all began from the time the education institution was founded up until present day";
}

<h1 class="contentPageH1">MEDIX HISTORY</h1>
<ol class="breadcrumb">
    <li class="contentp">@Html.ActionLink("Home", "Index", "Home")</li>
    <li class="contentp">@Html.ActionLink("About Medix", "Index", "DiscoverMedix")</li>
    <li class="active contentp">Medix History</li>
</ol>


<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="contentH1"><span class="glyphicon glyphicon-flag"></span>&nbsp;1969</h2>
    </div>
    <div class="panel-body">
        <p class="contentp">
            Medix College was founded and began its quest in the training of Quality Healthcare Professionals.
        </p>
    </div>
</div>


<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="contentH1"><span class="glyphicon glyphicon-flag"></span>&nbsp;1993</h2>
    </div>
    <div class="panel-body">
        <p class="contentp">
            Medix College purchases the former Southwestern Business College, which had served London students

            with courses in accounting, secretarial etc. New Medix training programs are Medical Office

            Administrator and introductory computer courses. Southwestern Business College/Medix College is

            conceived and located in 5000 sq. feet of classroom/training space in Oxbury Mall. Southwestern Medix

            trained approx. 90 students in 1993.        </p>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="contentH1"><span class="glyphicon glyphicon-flag"></span>&nbsp;1994</h2>
    </div>
    <div class="panel-body">
        <p class="contentp">
            Doctors Office/Medical Lab Assistant and Dental Assistant courses are added to the programs offered.

            Training increases to over 200 students this year. Southwestern Medix expands their facility from 5000

            to 7500 sq. ft.
        </p>
    </div>
</div>


<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="contentH1"><span class="glyphicon glyphicon-flag"></span>&nbsp;1995</h2>
    </div>
    <div class="panel-body">
        <p class="contentp">
            The need for specialized training in Healthcare increases. Southwestern Medix places students at

            London Health Science Center and other laboratories in the London area. Dental students spend part of

            their training course at U.W.O. Faculty of Medicine and Dentistry. Practical training in the U.W.O. dental

            clinic enhances skills and allows students to obtain hands on experience. This training continues today.
        </p>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="contentH1"><span class="glyphicon glyphicon-flag"></span>&nbsp;1996</h2>
    </div>
    <div class="panel-body">
        <p class="contentp">
            More expansion!! Southwestern Medix adds Chiropractic Office Assistant and Personal Support Worker

            programs to their prospectus. At this time, Medix students are finding employment opportunities in

            doctors offices, walk-in clinics, nursing homes, chiropractic clinics, hospitals, laboratories and various

            dental clinics and offices across Ontario and other provinces.
        </p>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="contentH1"><span class="glyphicon glyphicon-flag"></span>&nbsp;1997</h2>
    </div>
    <div class="panel-body">
        <p class="contentp">
            Medix College expands to Milton to offer the Personal Support Worker program as the need for in home

            and long-term care services increase due to an aging population and a shortage of workers. Three years

            later the school is moved to Brantford. 
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="contentH1"><span class="glyphicon glyphicon-flag"></span>&nbsp;1998 | 1999</h2>
    </div>
    <div class="panel-body">
        <p class="contentp">
            Medix College responds to Ontario regulations and adds to their Dental program by offering Level II

            duties. Level I Dental Assistants from all parts of Ontario, travel to London to receive upgrade training.
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="contentH1"><span class="glyphicon glyphicon-flag"></span>&nbsp;2000</h2>
    </div>
    <div class="panel-body">
        <p class="contentp">
            Y2K arrives, Medix College survives and prospers. Medix College acquires Health Care Vocational Centers

            (HCVC). Locations in Ottawa, Toronto and Scarborough are welcomed into the Medix family. Medix

            College also expands to Brantford and offers the Personal Support Worker program. Medix College

            moved into the direction of Mental Health and starts to provide training for Community Service Workers

            at the Brantford Location.
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="contentH1"><span class="glyphicon glyphicon-flag"></span>&nbsp;2001</h2>
    </div>
    <div class="panel-body">
        <p class="contentp">
            Plans for future expansion begin. Medix decides to increase their space in Oxbury Mall and make it

            home for at least 10 additional years.
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="contentH1"><span class="glyphicon glyphicon-flag"></span>&nbsp;2002</h2>
    </div>
    <div class="panel-body">
        <p class="contentp">
            Medix adds Community Service Worker and Pharmacy Technician programs to their London Campus.

            Londons only specialized healthcare trainer now offers 7 programs. Medix opens new campus in

            Kitchener and starts training Personal Support Workers.
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="contentH1"><span class="glyphicon glyphicon-flag"></span>&nbsp;2003</h2>
    </div>
    <div class="panel-body">
        <p class="contentp">
            Our tenth anniversary in London!!! Medix has now expanded to over 11,000 sq.ft. in Oxbury Mall and

            trains over 350 students per year, providing a state of the art training facility for Intra Oral Dental

            Assistants, Medical Office Administrators, Personal Support Workers, Community Service Workers,

            Medical Lab Assistants/Technicians, Chiropractic Office Assistants, and Pharmacy Technicians. In

            addition to London.
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="contentH1"><span class="glyphicon glyphicon-flag"></span>&nbsp;2004</h2>
    </div>
    <div class="panel-body">
        <p class="contentp">
            In our eleventh year, healthcare training is booming! and with Medix Colleges in Brantford, Kitchener,

            Scarborough, and Toronto we are able to help the demand and this makes Medix one of the largest

            health trainers in Ontario.
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="contentH1"><span class="glyphicon glyphicon-flag"></span>&nbsp;2005</h2>
    </div>
    <div class="panel-body">
        <p class="contentp">
            Medix Toronto experiences record growth and decides to welcome this growth by relocating to the

            Lawrence Square Mall and we now occupy 14,000 sq ft on the subway line to better serve the city of

            Toronto for the next 15 years!
    </div>
</div>
        
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="contentH1"><span class="glyphicon glyphicon-flag"></span>&nbsp;2006</h2>
    </div>
    <div class="panel-body">
        <p class="contentp">
            Medix Scarborough follows and acquires 14,000 sq ft in Scarborough at Lawrence East & Birchmount

            and completely renovates creating a state of the art training institute to better serve the city of

            Scarborough for years to come.
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="contentH1"><span class="glyphicon glyphicon-flag"></span>&nbsp;2007</h2>
    </div>
    <div class="panel-body">
        <p class="contentp">
            More Growth and Medix Toronto acquires 6000 sqft on the retail level and adding a Massage Therapy

            Clinic and a Career & Placement Services Department making it the largest dedicated Private Healthcare

            School in the Medix Family.
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="contentH1"><span class="glyphicon glyphicon-flag"></span>&nbsp;2008</h2>
    </div>
    <div class="panel-body">
        <p class="contentp">
            Our 15 year anniversary in Ontario starts and to celebrate and continue growth Medix Online is created

            to make available continuing healthcare education for working professionals across the province and

            eventually worldwide.
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="contentH1"><span class="glyphicon glyphicon-flag"></span>&nbsp;2009</h2>
    </div>
    <div class="panel-body">
        <p class="contentp">
            Medix continues its growth by acquiring ABMT College of Canada in Brampton Ontario, this move

            completes the trilogy of Medix College campuses that serve the GTA.
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="contentH1"><span class="glyphicon glyphicon-flag"></span>&nbsp;2012</h2>
    </div>
    <div class="panel-body">
        <p class="contentp">
            Medix acquires its Stage One CETAC recognition at its GTA ( Brampton, Scarborough, and Toronto )

            campuses.
    </div>
</div>

<br />

MedixCollege/Views/DiscoverMedix/Index.cshtml
@{
    Layout = "~/Views/DiscoverMedix/_DiscoverMedixLayout.cshtml";
}

@{
    ViewBag.Title = "Discover Medix";
    ViewBag.PageDescription = "Learn more about Medix College and why programs offered at this Private Career College helps graduates train for health care professions";
}

    <h1 class="contentPageH1">DISCOVER MEDIX</h1>
<ol class="breadcrumb">
    <li class="contentp">@Html.ActionLink("Home", "Index", "Home")</li>
    <li class="active contentp">Discover Medix</li>
</ol>

<blockquote class="contentBlockquote">
    <h2 class="contentPageH1">"To service with excellence the needs of our community and the needs of our graduates by matching skills"</h2>
</blockquote>

<br />
<div class="panel panel-default">
    <div class="panel-heading">
        <h1 class="contentH1">Medix College Overview</h1>
    </div>
    <div class="panel-body">
        <p class="contentp">
            For over 40 years Medix College has been providing industry leading healthcare career training for those
            looking to become medical professionals. Currently Medix College has six (6) campuses across Ontario
            with each of them featuring state-of-the-art facilities.

            <br /><br />

            Medix College believes in helping students achieve
            quality education quickly. All of our students receive hands-on, practical courses designed to quickly get
            you started on your chosen career path. We are committed to individuals seeking career-oriented
            programs leading directly to a successful career! Medix is the clear choice for those looking to change
            their life today, in addition, Medix College also provides online certificate programs to aid you in your
            quest to have the career you’ve always wanted.

            <br /><br />

            With the introduction part-time programs plus a range of online courses it’s now easier than ever to
            develop new skills and interests without disrupting your home, work or family commitments. If you’ve
            ever wanted to develop additional skills and interests, but never had the time, Medix College's part-time
            programs are for you! Look though our part-time programs for affordable courses that will fit with into
            your busy lifestyle, enhance your career and help you live life to the fullest.
        </p>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h1 class="contentH1">The Programs</h1>
    </div>
    <div class="panel-body">
        <p class="contentp">
            Medix College provides training in healthcare diploma programs preparing students for the growing
            healthcare industry in Canada. The objective of the program training is to equip the students with the
            most current theory and practical training necessary to become successful healthcare professionals.

            <br /><br />

            The curriculum relies on two fundamental principles; firstly, teach to foster an understanding of the material
            versus memorization of the material, and secondly, allowing the students to process information
            through practical experience. Practical experience is provided to our students through laboratories and
            an opportunity to shadow experienced workers in the field. Each campus has its own set of programs,
            which run throughout the year.
        </p>
    </div>
</div>

<br />

MedixCollege/Views/DiscoverMedix/_DiscoverMedixLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="heroWrapper">
        @ViewBag.HeroText
    </div>
    <div class="leftMenuWrapper col-sm-3 custom-collapse">
        <button class="btn-brand-white collapse-toggle visible-xs" type="button" data-toggle="collapse" data-parent="custom-collapse" data-target="#side-menu-discover">
            <span class=""><span class="glyphicon glyphicon-align-justify"></span></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        <ul class="leftMenu list-unstyled collapse" id="side-menu-discover">
            <li class="item contentH1-white"><span class="glyphicon glyphicon-home goldBorderSM"></span>&nbsp;@Html.ActionLink("Discover Medix", "Index", "DiscoverMedix")</li>
            <li class="item side-menu-h2"><span class="glyphicon glyphicon-share-alt goldColour"></span>&nbsp;@Html.ActionLink("Medix History", "History", "DiscoverMedix")</li>
            <li class="item side-menu-h2"><span class="glyphicon glyphicon-share-alt goldColour"></span>&nbsp;@Html.ActionLink("Virtual Tour", "VirtualTour", "DiscoverMedix")</li>
            <li class="item side-menu-h2"><span class="glyphicon glyphicon-share-alt goldColour"></span>&nbsp;@Html.ActionLink("Laptop Initiative", "LaptopInitiative", "DiscoverMedix")</li>
            <li class="item side-menu-h2"><span class="glyphicon glyphicon-share-alt goldColour"></span>&nbsp;@Html.ActionLink("Transcript Request", "TranscriptRequest", "DiscoverMedix")</li>
            <li class="item side-menu-h2"><span class="glyphicon glyphicon-share-alt goldColour"></span>&nbsp;@Html.ActionLink("Careers at Medix", "CareersAtMedix", "DiscoverMedix")</li>
            <li class="item side-menu-h2"><span class="glyphicon glyphicon-share-alt goldColour"></span>&nbsp;<a href="javascript: void(0)" onclick="popup('http://careercollegegroup.canpromo.com/Products.htm?CD=553')">Medix Store</a></li>


            <li class="item btn btn-brand btn-block spacer-top" id="askQuestion">Ask a Question</li>
            <li class="item btn btn-brand btn-block" id="requestCatalogue">Request Catalogue</li>
        </ul>
        <br />
    </div>
    <div class="col-sm-9 pull-right">
        <div class="contentBody">
            <div class="row bodyHeaderWrapper">
                @ViewBag.BodyHeaderText
            </div>
            <div class="row">
                <div class="col-sm-8 mid-padding">
                    @RenderBody()
                </div>

                <div class="col-sm-4">
                    <div class="row formWrapper overquestionsForm">
                        <br />
                        <h1 class="contentH1 text-center">
                            <span class="glyphicon glyphicon-comment blueGoldBorder"></span>&nbsp; Ask a Question
                        </h1>
                        <form id="discoverMedixQuestionsForm" name="discoverMedixQuestionsForm" class="questionsForm" method="post" action="/home/askquestion">
                            <input type="hidden" name="ORGID" value="240" />
                            <input type="hidden" name="MailListID" value="240001" />
                            <div class="input-group spacer-top">
                                <label class="pull-left contentp">First Name: <span class="text-danger">*</span></label>
                                <input type="text" class="form-control pull-right" name="FirstName">
                            </div>
                            <div class="input-group spacer-top">
                                <label class="pull-left contentp">Email: <span class="text-danger">*</span></label>
                                <input type="email" class="form-control pull-right" name="Email">
                            </div>
                            <div class="input-group spacer-top">
                                <label class="pull-left contentp">Location: <span class="text-danger">*</span></label>
                                <select class="form-control pull-right" name="CampusID">
                                    <option value="0">Select</option>
                                    <option value="246">Brampton</option>
                                    <option value="243">Brantford</option>
                                    <option value="242">Kitchener</option>
                                    <option value="244">London</option>
                                    <option value="241">Scarborough</option>
                                    <option value="240">Toronto</option>
                                </select>
                            </div>
                            <div class="input-group spacer-top">
                                <label class="pull-left contentp">Program: <span class="text-danger">*</span></label>
                                <select class="form-control pull-right" name="ProgramID">
                                    <option value="0">Select</option>
                                    <option value="38882">Anatomy &amp; Physiology</option>
                                    <option value="39877">Child and Youth Care with Addictions Support Worker</option>
                                    <option value="632">Community Service Worker</option>
                                    <option value="39478">CPR &amp; First Aid</option>
                                    <option value="818">Dental Level 2</option>
                                    <option value="38883">Dental Office Procedures (abel dent)</option>
                                    <option value="634">Developmental Service Worker</option>
                                    <option value="38526">Early Childhood Assistant</option>
                                    <option value="642">ECG</option>
                                    <option value="37255">Fitness &amp; Health Promotion</option>
                                    <option value="39162">Intramuscular Injection</option>
                                    <option value="627">Intra-Oral Dental Assistant </option>
                                    <option value="629">Massage Therapy</option>
                                    <option value="633">Medical Laboratory Assistant / Technician</option>
                                    <option value="630">Medical Office Administrator</option>
                                    <option value="1170">Medical Terminology</option>
                                    <option value="38887">Medical Transcription</option>
                                    <option value="39415">Mental Health &amp; Addictions</option>
                                    <option value="1169">OHIP Billing</option>
                                    <option value="631">Personal Support Worker</option>
                                    <option value="628">Pharmacy Assistant</option>
                                    <option value="636">Phlebotomy</option>
                                    <option value="1167">Principles of Nutrition</option>
                                    <option value="643">PSW Upgrading</option>
                                    <option value="1171">Thought Patterns</option>

                                </select>
                            </div>
                            <div class="input-group spacer-top">
                                <label class="pull-left contentp">Comments: </label>
                                <textarea class="form-control pull-right" name="Comment2"></textarea>
                            </div>
                            <div class="small-text spacer-top text-center grayColor contentp">
                                Please contact me with more information relating to the school and program(s). I understand I may cancel my consent at anytime.
                            </div>
                            <div class="text-center">
                                <input id="applyNowSubmit" type="submit" value="Submit" class="btn popup-form-button spacer-top btn-block" />
                            </div>
                        </form>
                    </div>
                    <div class="row sideWrapper">
                        <div class="sideHeader">
                            <h1 class="contentH1-main">@ViewBag.SideHeader</h1>
                        </div>
                        <div class="sideBody">
                            <div class="sideSubWrapper">
                                <div class="sideSubHeader">
                                    @ViewBag.SideSubHeader1
                                </div>
                                <div class="sideSubText">
                                    @ViewBag.SideSubText1
                                </div>
                            </div>
                            <div class="sideSubWrapper">
                                <div class="sideSubHeader">
                                    @ViewBag.SideSubHeader2
                                </div>
                                <div class="sideSubText">
                                    @ViewBag.SideSubText2
                                </div>
                            </div>
                            <div class="sideSubWrapper">
                                <div class="sideSubHeader">
                                    @ViewBag.SideSubHeader3
                                </div>
                                <div class="sideSubText">
                                    @ViewBag.SideSubText3
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <br />
</div>
<script>
    $(document).ready(function () {
        $('#applyOnline').click(function () {
            $('.popup-form-wrapper').hide();
            $('#applyNowWrapper').show();
            $('.form-overlay').slideDown()
        });

        $('#requestCatalogue').click(function () {
            $('.popup-form-wrapper').hide();
            $('#requestCatalogueWrapper').show();
            $('.form-overlay').slideDown()
        });

        $('#askQuestion').click(function () {
            $('.popup-form-wrapper').hide();
            $('#askQuestionWrapper').show();
            $('.form-overlay').slideDown()
        });
    });
</script>